import Image from "next/image";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="grid grid-cols-7 gap-4">
        
      <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
        <li>
          hello
        </li>
      </div>
    </main>
  );
}
